ARG tag=1.12.0
ARG pyVer=py36

# Base image
FROM deephdc/tensorflow:${tag}-${pyVer}

LABEL maintainer='Stefan Dlugolinsky'
LABEL version='0.3.1'
LABEL description='MODS (Massive Online Data Streams) - dev'

# What user branch to clone (!)
ARG branch=master

# Install ubuntu updates and related stuff
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && \
    apt-get install -y --no-install-recommends \
         git \
         curl

# install rclone
RUN curl https://downloads.rclone.org/rclone-current-linux-amd64.deb --output rclone-current-linux-amd64.deb && \
    dpkg -i rclone-current-linux-amd64.deb && \
    apt install -f && \
    rm rclone-current-linux-amd64.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

ENV LANG C.UTF-8

# Set the working directory
WORKDIR /srv

COPY scripts/build-n-run-deepaas.sh build-n-run-deepaas.sh

# Disable FLAAT authentication by default
ENV DISABLE_AUTHENTICATION_AND_ASSUME_AUTHENTICATED_USER yes

# Open DEEPaaS port
EXPOSE 5000

CMD tail -f /dev/null
