FROM ubuntu:18.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
	apt-get install -y --no-install-recommends \
		git \
		curl \
		mc \
		wget \
		vim \
		ssh \
		netcat \
		python3 \
		python3-setuptools \
		python3-pip \
		python3-wheel && \
	curl https://downloads.rclone.org/rclone-current-linux-amd64.deb --output rclone-current-linux-amd64.deb && \
	dpkg -i rclone-current-linux-amd64.deb && \
	apt install -f && \
	rm rclone-current-linux-amd64.deb && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /root/.cache/pip/* && \
	rm -rf /tmp/*

ENV LANG C.UTF-8

WORKDIR /srv

COPY scripts/build-n-run-deepaas.sh build-n-run-deepaas.sh

EXPOSE 5000

CMD tail -f /dev/null
